plugins {
	id 'maven-publish'
	id 'java'
	id 'com.enonic.xp.app'
	id "net.linguica.maven-settings" version "0.5"
	id 'pl.allegro.tech.build.axion-release' version '1.19.1'
}

version = scmVersion.version

compileJava.options.encoding = "UTF-8"

dependencies {
	compileOnly xplibs.api.core
	compileOnly xplibs.api.portal
	include "org.freemarker:freemarker:2.3.32"
	include "no.api.freemarker:freemarker-java8:2.1.0"
}

repositories {
	mavenCentral()
	xp.enonicRepo()
}

publishing {
	publications {
		maven( MavenPublication ) {
			groupId 'no.tine.xp'
			artifactId 'xp-lib-freemarker'
			version "$version"
			from components.java
		}
	}

	repositories {
		maven {
			url 'https://pkgs.dev.azure.com/tine-sa/_packaging/digitale-flater/maven/v1'
			name 'digitale-flater'
			authentication {
				basic(BasicAuthentication)
			}
		}
	}
}

//jar.archiveName = "${jar.baseName}.${jar.extension}"
